[project]
name = "gaia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dvc[s3]>=3.67.1",
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "numpy>=2.2.0",
    "pandas>=2.2.3",
    "tigramite>=5.2.7.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
